spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        highlight_sql: false
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 100
    database: mysql
  data:
    redis:
      host: 127.0.0.1   #${REDIS_URL}
      port: 6379



logging:
  level:
    org.hibernate.sql: warn
    org.hibernate.type.descriptor.sql: warn
    root: warn



jwt:
  prefix: 'Bearer '
  secret-key: ${KEY}
  access-token-validity-in-seconds: 15000
  refresh-token-validity-in-seconds: 259200
  access-header: Authentication
  refresh-header: Refresh

cookie:
  limit-time: 259200
  accepted-url: '/api/auth/reissue'
  cookie-name: Refresh
  domain: localhost





aws:
  s3:
    bucket:
      name: ${SHAREDUCK_S3_BUCKET}
    postImage.root: ${SHAREDUCK_POSTIMAGE_ROOT_PATH}
  cloudfront:
    host: ${SHAREDUCK_CLOUDFRONT_HOST}





server:
  port: 8080
  ssl:
    key-store: ${SHAREDUCK_KEY_STORE}
    key-store-password: ${SHAREDUCK_KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
